services:
  - type: web
    name: earthquake-bot
    env: docker
    plan: free # 必要に応じてプランを変更（例: starter, pro）
    region: oregon # 必要に応じてリージョンを変更
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    healthCheckPath: /
